# Generated by Django 5.0.6 on 2026-07-25 18:14

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('customer', 'Mijoz'), ('supplier', 'Yetkazib beruvchi')], max_length=10, verbose_name='Turi')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Telefon')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('default_currency', models.CharField(choices=[('UZS', "UZS - O'zbek so'mi"), ('USD', 'USD - AQSH dollari'), ('EUR', 'EUR - Yevro'), ('RUB', 'RUB - Rossiya rubli')], default='UZS', max_length=3, verbose_name='Asosiy valyuta')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kontragent',
                'verbose_name_plural': 'Mijoz / Yetkazib beruvchilar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDebt',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('direction', models.CharField(choices=[('debitor', 'Debitor (bizga qarzdor)'), ('kreditor', 'Kreditor (biz qarzdormiz)')], max_length=10, verbose_name="Yo'nalishi")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Summa')),
                ('currency', models.CharField(choices=[('UZS', "UZS - O'zbek so'mi"), ('USD', 'USD - AQSH dollari'), ('EUR', 'EUR - Yevro'), ('RUB', 'RUB - Rossiya rubli')], default='UZS', max_length=3, verbose_name='Valyuta')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name="To'langan summa")),
                ('due_date', models.DateField(verbose_name="To'lov muddati")),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('due_soon', 'Muddati yaqin'), ('overdue', "Muddati o'tgan"), ('closed', "To'liq yopilgan")], default='active', max_length=10, verbose_name='Holati')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.party', verbose_name='Kontragent')),
            ],
            options={
                'verbose_name': 'historical Qarzdorlik',
                'verbose_name_plural': 'historical Debitor / Kreditor qarzdorlik',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('debitor', 'Debitor (bizga qarzdor)'), ('kreditor', 'Kreditor (biz qarzdormiz)')], max_length=10, verbose_name="Yo'nalishi")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Summa')),
                ('currency', models.CharField(choices=[('UZS', "UZS - O'zbek so'mi"), ('USD', 'USD - AQSH dollari'), ('EUR', 'EUR - Yevro'), ('RUB', 'RUB - Rossiya rubli')], default='UZS', max_length=3, verbose_name='Valyuta')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name="To'langan summa")),
                ('due_date', models.DateField(verbose_name="To'lov muddati")),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('due_soon', 'Muddati yaqin'), ('overdue', "Muddati o'tgan"), ('closed', "To'liq yopilgan")], default='active', max_length=10, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='parties.party', verbose_name='Kontragent')),
            ],
            options={
                'verbose_name': 'Qarzdorlik',
                'verbose_name_plural': 'Debitor / Kreditor qarzdorlik',
                'ordering': ['due_date'],
            },
        ),
    ]
