# Generated by Django 5.0.6 on 2026-07-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mening kompaniyam', max_length=255, verbose_name='Kompaniya nomi')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo')),
                ('base_currency', models.CharField(default='UZS', max_length=3, verbose_name='Asosiy valyuta')),
                ('inn', models.CharField(blank=True, max_length=32, verbose_name='STIR')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Telefon')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=12, max_digits=5, verbose_name='QQS stavkasi (%)')),
                ('profit_tax_rate', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name="Foyda solig'i stavkasi (%)")),
                ('notify_browser_push', models.BooleanField(default=True, verbose_name='Brauzer bildirishnomalari yoqilgan')),
            ],
            options={
                'verbose_name': 'Kompaniya sozlamalari',
                'verbose_name_plural': 'Kompaniya sozlamalari',
            },
        ),
    ]
