# Generated by Django 5.0.6 on 2026-07-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=3, verbose_name='Valyuta')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='Kursi (UZS)')),
                ('diff', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Kurs farqi')),
                ('date', models.DateField(verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'Valyuta kursi',
                'verbose_name_plural': 'Valyuta kurslari (Markaziy bank)',
                'ordering': ['-date', 'currency_code'],
                'unique_together': {('currency_code', 'date')},
            },
        ),
    ]
