# Generated by Django 5.0.6 on 2026-07-25 18:14

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('type', models.CharField(choices=[('income', 'Daromad'), ('expense', 'Xarajat')], max_length=10, verbose_name='Turi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'unique_together': {('name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Daromad'), ('expense', 'Xarajat')], max_length=10, verbose_name='Turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Summa')),
                ('currency', models.CharField(choices=[('UZS', "UZS - O'zbek so'mi"), ('USD', 'USD - AQSH dollari'), ('EUR', 'EUR - Yevro'), ('RUB', 'RUB - Rossiya rubli')], default='UZS', max_length=3, verbose_name='Valyuta')),
                ('date', models.DateField(verbose_name='Sana')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Izoh')),
                ('attachment', models.TextField(blank=True, max_length=100, null=True, verbose_name='Chek/fayl')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.category', verbose_name='Kategoriya')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Operatsiya',
                'verbose_name_plural': 'historical Daromad va xarajatlar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Daromad'), ('expense', 'Xarajat')], max_length=10, verbose_name='Turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Summa')),
                ('currency', models.CharField(choices=[('UZS', "UZS - O'zbek so'mi"), ('USD', 'USD - AQSH dollari'), ('EUR', 'EUR - Yevro'), ('RUB', 'RUB - Rossiya rubli')], default='UZS', max_length=3, verbose_name='Valyuta')),
                ('date', models.DateField(verbose_name='Sana')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Izoh')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='transactions/%Y/%m/', verbose_name='Chek/fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.category', verbose_name='Kategoriya')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operatsiya',
                'verbose_name_plural': 'Daromad va xarajatlar',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
