# Generated by Django 5.0.6 on 2026-07-25 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('unit', models.CharField(default='dona', max_length=32, verbose_name="O'lchov birligi")),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Qoldiq')),
                ('min_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Minimal qoldiq')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Narxi')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', 'Kirim'), ('out', 'Chiqim')], max_length=5, verbose_name='Turi')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Miqdori')),
                ('date', models.DateField(verbose_name='Sana')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='warehouse.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Ombor harakati',
                'verbose_name_plural': 'Kirim / Chiqim',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
