# Generated by Django 5.0.6 on 2026-07-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('date', models.DateField(verbose_name='Sana')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Soliq kalendari yozuvi',
                'verbose_name_plural': 'Soliq kalendari',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TaxRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('vat', 'QQS'), ('profit', "Foyda solig'i"), ('other', 'Boshqa')], max_length=10, verbose_name='Soliq turi')),
                ('period', models.CharField(max_length=32, verbose_name='Davr (masalan: 2026-Iyul)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Summa')),
                ('due_date', models.DateField(verbose_name="Topshirish/to'lov muddati")),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'langan")),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Soliq yozuvi',
                'verbose_name_plural': 'Soliqlar',
                'ordering': ['due_date'],
            },
        ),
    ]
