# Generated by Django 5.0.6 on 2026-07-25 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.Sh.')),
                ('position', models.CharField(max_length=150, verbose_name='Lavozim')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Telefon')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Oylik maosh')),
                ('hired_date', models.DateField(blank=True, null=True, verbose_name='Ishga qabul sanasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('salary', 'Oylik'), ('bonus', 'Bonus'), ('penalty', 'Jarima'), ('advance', 'Avans')], max_length=10, verbose_name='Turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa')),
                ('date', models.DateField(verbose_name='Sana')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='hr.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Maosh yozuvi',
                'verbose_name_plural': 'Maosh tarixi',
                'ordering': ['-date'],
            },
        ),
    ]
