# Generated by Django 5.0.6 on 2026-07-25 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, unique=True, verbose_name='Shartnoma raqami')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Summa')),
                ('currency', models.CharField(choices=[('UZS', "UZS - O'zbek so'mi"), ('USD', 'USD - AQSH dollari'), ('EUR', 'EUR - Yevro'), ('RUB', 'RUB - Rossiya rubli')], default='UZS', max_length=3, verbose_name='Valyuta')),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Fayl')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='parties.party', verbose_name='Kontragent')),
            ],
            options={
                'verbose_name': 'Shartnoma',
                'verbose_name_plural': 'Shartnomalar',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, unique=True, verbose_name='Hisob-faktura raqami')),
                ('date', models.DateField(verbose_name='Sana')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Summa')),
                ('currency', models.CharField(choices=[('UZS', "UZS - O'zbek so'mi"), ('USD', 'USD - AQSH dollari'), ('EUR', 'EUR - Yevro'), ('RUB', 'RUB - Rossiya rubli')], default='UZS', max_length=3, verbose_name='Valyuta')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('file', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Fayl (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='parties.party', verbose_name='Kontragent')),
            ],
            options={
                'verbose_name': 'Hisob-faktura',
                'verbose_name_plural': 'Hisob-fakturalar',
                'ordering': ['-date'],
            },
        ),
    ]
